// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkhO7Dl3_fPyuJs4jEVRMYBIglw5Nn2Ac',
    appId: '1:202819038937:android:e13b654e44ba4807c418c8',
    messagingSenderId: '202819038937',
    projectId: 'projet-annuel-flutter-firebase',
    databaseURL: 'https://projet-annuel-flutter-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projet-annuel-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz5WJ-D0OBwSSitk832WsfAC1LCEK_cNI',
    appId: '1:202819038937:ios:5b05019fd6527175c418c8',
    messagingSenderId: '202819038937',
    projectId: 'projet-annuel-flutter-firebase',
    databaseURL: 'https://projet-annuel-flutter-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'projet-annuel-flutter-firebase.appspot.com',
    androidClientId: '202819038937-os7080qc64ri86mj4rvpuh63uq9d7jd9.apps.googleusercontent.com',
    iosClientId: '202819038937-o4bpno3akafmuaasbj4egfgtaoavibpl.apps.googleusercontent.com',
    iosBundleId: 'com.esgi.flutter.firebase.projetannuel.projetAnnuelFlutterFirebase4Moc',
  );
}
